/// A map of all available currencies
class AllCurrencies {
  static Map<String, Map<String, String>> currencies = {
    'ARS': {'Argentine Peso': '🇦🇷'},
    'USD': {'American Dollar': '🇺🇸'},
    'AUD': {'Australian Dollar': '🇦🇺'},
    'BCH': {'Bitcoin Cash': '💰'},
    'BGN': {'Bulgarian Lev': '🇧🇬'},
    'BNB': {'Binance Coin': '💰'},
    'BRL': {'Brazilian Real': '🇧🇷'},
    'BTC': {'Bitcoin': '💰'},
    'CAD': {'Canadian Dollar': '🇨🇦'},
    'CHF': {'Swiss Franc': '🇨🇭'},
    'CNY': {'Chinese Yuan': '🇨🇳'},
    'CZK': {'Czech Republic Koruna': '🇨🇿'},
    'DKK': {'Danish Krone': '🇩🇰'},
    'DOGE': {'Dogecoin': '💰'},
    'DZD': {'Algerian Dinar': '🇩🇿'},
    'ETH': {'Ethereum': '💰'},
    'EUR': {'Euro': '🇪🇺'},
    'GBP': {'British Pound Sterling': '🇬🇧'},
    'HKD': {'Hong Kong Dollar': '🇭🇰'},
    'HRK': {'Croatian Kuna': '🇭🇷'},
    'HUF': {'Hungarian Forint': '🇭🇺'},
    'IDR': {'Indonesian Rupiah': '🇮🇩'},
    'ILS': {'Israeli New Sheqel': '🇮🇱'},
    'INR': {'Indian Rupee': '🇮🇳'},
    'ISK': {'Icelandic Króna': '🇮🇸'},
    'JPY': {'Japanese Yen': '🇯🇵'},
    'KRW': {'South Korean Won': '🇰🇷'},
    'LTC': {'Litecoin': '💰'},
    'MAD': {'Moroccan Dirham': '🇲🇦'},
    'MXN': {'Mexican Peso': '🇲🇽'},
    'MYR': {'Malaysian Ringgit': '🇲🇾'},
    'NOK': {'Norwegian Krone': '🇳🇴'},
    'NZD': {'New Zealand Dollar': '🇳🇿'},
    'PHP': {'Philippine Peso': '🇵🇭'},
    'PLN': {'Polish Zloty': '🇵🇱'},
    'RON': {'Romanian Leu': '🇷🇴'},
    'RUB': {'Russian Ruble': '🇷🇺'},
    'SEK': {'Swedish Krona': '🇸🇪'},
    'SGD': {'Singapore Dollar': '🇸🇬'},
    'THB': {'Thai Baht': '🇹🇭'},
    'TRY': {'Turkish Lira': '🇹🇷'},
    'TWD': {'New Taiwan Dollar': '🇹🇼'},
    'XRP': {'Ripple': '💰'},
    'ZAR': {'South African Rand': '🇿🇦'},
  };
}
